# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registy-url: ${{secrets.REGISTRY_URL}}
      - name: nodejs install
        run: npm install 
      - name: nodejs clean install
        run: npm clean-install
      - name: Nodejs Build
        run: npm run build --if-present
      # - name: Nodejs test
      #   run: npm test
      - name: npm log in
        run: npm config set registry=${{secrets.REGISTRY_URL}}
      - name: npm login
        # run: npm login -u ${{secrets.NEXUS_USERNAME}} -p ${{secrets.NEXUS_PASSWORD}}
        run: echo "//${{secrets.REGISTRY_URL}}/:_auth=${{secrets.NEXUS_USERNAME}}:${{secrets.NEXUS_PASSWORD}}" > ~/.npmrc

      - name: Publish
        run: npm publish
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}